# Generated by Django 5.0.6 on 2024-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accounts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
