# Generated by Django 5.0.6 on 2024-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_accounts_email_alter_accounts_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
