# Generated by Django 5.0.6 on 2024-07-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_accounts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='photo',
            field=models.ImageField(default='uploads/base_avatar.jpg', upload_to='uploads/'),
        ),
    ]
