# Generated by Django 5.0.6 on 2024-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_accounts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='photo',
            field=models.ImageField(default='uploads/base_avatar.jpg', null=True, upload_to='uploads/'),
        ),
    ]
