# Generated by Django 5.0.6 on 2024-07-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_accounts_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='upldfile/')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
