# Generated by Django 5.0.6 on 2024-07-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='frame_size',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='number_of_rating',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='overall_rating',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='power_connector',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='powering',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='propeller_size',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='transmitter_protocol',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='version',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='video_transmission',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
