# Generated by Django 5.0.6 on 2024-07-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_products_brand_alter_products_frame_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.products'),
        ),
    ]
