# Generated by Django 5.0.6 on 2024-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_images_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default='По запросу', max_length=50),
        ),
    ]
