# Generated by Django 5.0.7 on 2024-07-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
